# -*- coding: utf-8 -*-
# Enriquece bank.json com descricao por-clip. Roda no fim (depois de preencher DESC).
import json

DESC = {
# ---- remotion (prompts exatos) ----
"remotion-01":"mao de robo IA tocando uma claquete de cinema que se desfaz em particulas",
"remotion-02":"streams de codigo ambar fluindo numa tela escura (rio de codigo)",
"remotion-03":"linhas de codigo virando uma timeline de edicao de video",
"remotion-04":"explosao de particulas formando grafico de crescimento viral",
"remotion-05":"timeline de edicao com marcadores de corte e tesoura",
"remotion-06":"caneta de luz desenhando sozinha um quadro de video (video que se escreve)",
"remotion-07":"planilha de luz virando grafico de barras 3D animado",
"remotion-08":"dezenas de cards de video se multiplicando numa grade (videos personalizados em massa)",
"remotion-09":"cerebro de IA montando blocos de codigo que viram um video polido",
"remotion-10":"motor/engrenagem de luz gerando quadros de video",
"remotion-11":"guia/livro de luz aberto com passos surgindo das paginas",
"remotion-12":"mesa de criador com monitor renderizando um video abstrato",
"remotion-13":"dashboard de dados com graficos e motion graphics flutuando",
"remotion-14":"abertura de marca: formas geometricas de luz se acendendo",
"remotion-15":"faisca correndo num circuito ate um botao de play (final)",
# ---- crm ----
"crm-01":"calendario com moedas ambar escorrendo todo mes (assinatura cara/aluguel)",
"crm-02":"estrela open-source explodindo num ceu com constelacao (estrelas do GitHub)",
"crm-03":"dashboard de CRM moderno com cards de contato e funil",
"crm-04":"rack de servidor com escudo de luz (self-hosted, o dado e seu)",
"crm-05":"servidor barato rodando uma rede enorme de contatos (usuarios infinitos)",
"crm-06":"cerebro de IA remodelando os paineis de um CRM (customizacao)",
"crm-07":"blocos modulares (funil, automacao, campo) se encaixando num CRM",
"crm-08":"maos de luz instalando um servidor com chave de fenda (setup)",
"crm-09":"guia/livro de luz com passos de instalacao",
"crm-10":"balao de fala saindo de um chat (enviar/comentar)",
"crm-11":"duas colunas de luz comparando custo (uma escorrendo moedas, outra estavel)",
"crm-12":"globo de nos de contato pulsando (rede de clientes)",
"crm-13":"cadeado abrindo um cofre de dados (seu dado e seu)",
"crm-14":"faisca correndo num circuito ate um icone de CRM (final)",
# ---- assistir ----
"assistir-01":"olho de IA abrindo dentro de um botao de play (IA que assiste video)",
"assistir-02":"link/corrente de video sendo puxado pra dentro de uma esfera de IA",
"assistir-03":"cerebro de IA absorvendo quadros de video e virando linhas de texto (transcrever/aprender)",
"assistir-04":"botao de play irradiando ondas sobre uma grade de thumbnails (plataforma de video)",
"assistir-05":"film strip longo comprimindo num card de resumo (2h em 2min)",
"assistir-06":"plugue de conector encaixando numa esfera de IA (conector MCP)",
"assistir-07":"quatro tokens de dados fluindo de um site pra uma IA (setup, 4 dados)",
"assistir-08":"link conectando uma conta a uma esfera de IA (vincular conta)",
"assistir-09":"checkmark dentro de um toggle de permissao (sempre permitir)",
"assistir-10":"guia/livro com cards de passo a passo (prints)",
"assistir-11":"lupa sobre o video de um concorrente (analisar estrategia)",
"assistir-12":"sala de aula de luz, IA ensinando conceitos (aprender e ensinar)",
"assistir-13":"faisca correndo num circuito ate um botao de play (final)",
# ---- tag ----
"tag-01":"arroba @ se acendendo num chat de equipe escuro (lancamento)",
"tag-02":"robo de IA amigavel sentando entre baloes de chat (novo colega de time)",
"tag-03":"mao de luz tocando a tag @ num colega de IA num thread (delegar)",
"tag-04":"robo de IA trabalhando enquanto silhueta de pessoa sai pra outra tarefa (trabalho paralelo)",
"tag-05":"dois cenarios: resumo de reuniao e card de lead organizados por uma IA",
"tag-06":"robo de IA como colega de verdade numa mesa (nao bot escondido)",
"tag-07":"trabalhador de IA disponivel num hub de chat pulsando (sempre on)",
"tag-08":"explosao de particulas formando grafico de views (post viral)",
"tag-09":"guia/livro com passos de ativacao",
"tag-10":"painel de controle com toggles de acesso a canais/ferramentas (permissao)",
"tag-11":"rede de membros do time conectada a uma IA central no chat",
"tag-12":"faisca correndo num circuito ate a arroba @ (final)",
# ---- 5-minutos (thumbs) ----
"5-minutos-01":"relogio de pulso de luxo iluminado (tempo)",
"5-minutos-02":"cronometro no fim de uma estrada de luz (tempo correndo)",
"5-minutos-03":"explosao de particulas ambar (burst/urgencia)",
"5-minutos-04":"roleta de cassino girando (aposta/sorte)",
"5-minutos-05":"pepita/cristal ambar numa colher (valor/pouco)",
"5-minutos-06":"cofre/porta abrindo com luz saindo (oportunidade)",
"5-minutos-07":"chama de luz saindo de um celular (energia no celular)",
"5-minutos-08":"pilha de checkmarks de luz sobre um celular (tarefas concluidas)",
"5-minutos-09":"tela de celular com icones/notificacoes ambar (app)",
"5-minutos-10":"chama de luz saindo de um celular (energia no celular)",
"5-minutos-11":"pilha de checkmarks de luz sobre um celular (tarefas concluidas)",
"5-minutos-12":"tela de celular com icones/notificacoes ambar (app)",
# ---- ai-slop (thumbs) ----
"ai-slop-01":"fileira de telas/cartoes brancos iguais em perspectiva (mesmice/padrao)",
"ai-slop-02":"um card roxo destacado sobre fundo escuro (destaque/identidade)",
"ai-slop-03":"cards de tech derretendo com perninhas (design generico derretendo)",
"ai-slop-04":"portal/anel escuro com folhas (vazio/buraco)",
"ai-slop-05":"pilha de papeis/folhas desfocada (documentos)",
"ai-slop-06":"feixe de luz atingindo uma superficie, faisca (impacto/criacao)",
"ai-slop-07":"moldura/losango de neon ambar (forma geometrica)",
"ai-slop-08":"cards/tarots de luz numa fileira com onda de luz (baralho/cartas)",
"ai-slop-09":"livro/placa escura com simbolo ambar gravado (capa/marca)",
"ai-slop-10":"celular com bolhas/icones ambar saindo (notificacoes no celular)",
"ai-slop-11":"cristal/esfera ambar grande iluminada (cristal/destaque)",
"ai-slop-12":"celular com bolhas/icones ambar saindo (notificacoes no celular)",
"ai-slop-13":"celular inclinado com bolhas/icones ambar (notificacoes)",
# ---- claude-smb (thumbs) ----
"claude-smb-01":"pilha gigante de papeis brilhando (papelada/burocracia)",
"claude-smb-02":"caixa aberta com luz saindo (lancamento/abrir)",
"claude-smb-03":"fileira de robos de IA enfileirados (exercito de agentes)",
"claude-smb-04":"robo de IA segurando um documento de luz (robo processando papel)",
"claude-smb-05":"robo de IA na frente de fileiras de notas/dinheiro (robo + boleto/cobranca)",
"claude-smb-06":"robo de IA lendo/segurando um documento (robo revisando contrato)",
"claude-smb-07":"mao humana apertando um botao ao lado de um robo (ativar robo)",
"claude-smb-08":"pessoa e robo de IA trabalhando juntos numa mesa (humano + IA)",
"claude-smb-09":"laptop com dashboard/relatorio de luz flutuando (relatorio/dados)",
"claude-smb-10":"celular com bolhas de chat saindo (mensagens/WhatsApp)",
"claude-smb-11":"robo de IA trabalhando num escritorio com pessoas ao fundo (IA no escritorio)",
"claude-smb-12":"celular com bolhas de chat ambar (mensagens)",
# ---- contratacao-errada (thumbs) ----
"contratacao-errada-01":"mao mexendo num monitor com texto (analisar curriculo/tela)",
"contratacao-errada-02":"pilha de envelopes/cartas com coroas (candidatos)",
"contratacao-errada-03":"pessoa trabalhando a noite, telas com numeros (trabalho/dados)",
"contratacao-errada-04":"homem de terno serio numa mesa com luminaria (chefe/entrevista/decisao)",
"contratacao-errada-05":"papeis em chamas 'salary cost' (custo queimando/dinheiro perdido)",
"contratacao-errada-06":"mao tocando um circuito que se ramifica em luz (decisao/conexao)",
"contratacao-errada-07":"palco com plateia e palestrante (apresentacao/palco)",
# ---- desvio-fable (thumbs) ----
"desvio-fable-01":"orbe ambar dentro de um anel (nucleo de IA)",
"desvio-fable-02":"rajada de particulas ambar fluindo (energia/desvio)",
"desvio-fable-03":"onda de luz sobre um laptop (dados fluindo)",
"desvio-fable-04":"feixe de luz horizontal sobre superficie (energia/streak)",
"desvio-fable-05":"portal/corredor de luz ambar (portal)",
"desvio-fable-06":"estrutura geometrica de luz ambar (arquitetura de luz)",
"desvio-fable-07":"portal/corredor de luz ambar (portal)",
"desvio-fable-08":"laptop com dashboard circular de luz (dados/relatorio)",
"desvio-fable-09":"esfera de vidro com nucleo ambar (orbe de IA)",
"desvio-fable-10":"celular com orbes/bolhas ambar saindo (IA no celular)",
"desvio-fable-11":"celular com orbe central e bolhas (IA no celular)",
"desvio-fable-12":"celular com orbes ambar saindo (IA no celular)",
"desvio-fable-13":"celular com dois orbes conectados (conexao/IA no celular)",
# ---- fantasma (thumbs) ----
"fantasma-01":"mao tocando uma bola de cristal vermelha (invocacao/oraculo)",
"fantasma-02":"pergaminho/folha de luz ambar (documento/texto oculto)",
"fantasma-03":"maquina/cubo de luz expelindo um documento (IA processando documento)",
"fantasma-04":"mao de marionetista controlando um cubo com fios (manipulacao/controle oculto)",
"fantasma-05":"cadeado explodindo/quebrando (seguranca quebrada)",
"fantasma-06":"figura fantasma humanoide de fogo emergindo (comando oculto/fantasma)",
"fantasma-07":"nucleo de energia com icones (email, engrenagem) conectados (sistema/injecao)",
"fantasma-08":"escudo/pergaminho de luz ambar quebrando rocha (defesa)",
"fantasma-09":"laptop com escudo de luz (protecao/seguranca)",
"fantasma-10":"celular com fragmentos ambar saindo (dados saindo)",
"fantasma-11":"capsula de luz com nucleo entre dois guardas (cofre guardado)",
"fantasma-12":"celular com bolhas ambar saindo (mensagens/dados)",
# ---- goal (thumbs) ----
"goal-01":"dedo apertando tecla de teclado iluminada (comando/enter)",
"goal-02":"esfera/lua ambar fumegante numa mesa (nucleo/objetivo)",
"goal-03":"robo humanoide correndo numa estrada (perseguir meta)",
"goal-04":"linha de luz no horizonte (linha de chegada)",
"goal-05":"placa de circuito com trilha de luz (processamento)",
"goal-06":"pilha de checkmarks de luz (tarefas concluidas)",
"goal-07":"mao robotica digitando num teclado com HUD (IA codando)",
"goal-08":"pernas roboticas correndo sobre texto de luz (sprint)",
"goal-09":"pessoa dormindo enquanto telas trabalham no quarto (trabalho automatico)",
"goal-10":"celular com icones/moedas ambar saindo (app/resultado)",
"goal-11":"bola entrando no gol/rede (meta atingida)",
"goal-12":"celular com icones ambar saindo (app/resultado)",
# ---- fable-maestro (thumbs) ----
"fable-maestro-01":"vela/tubo de luz com faiscas saindo (energia/pavio)",
"fable-maestro-02":"torre de esferas empilhadas (pilha/equilibrio)",
"fable-maestro-03":"esfera grande pontilhada de luz numa caixa de vidro (globo de dados)",
"fable-maestro-04":"lente/cilindro de metal sobre um papel (maquina/prensa)",
"fable-maestro-05":"homem de terno de costas com maos na cabeca (estresse/frustracao)",
"fable-maestro-06":"rastro de luz ambar curvo (energia/movimento)",
"fable-maestro-07":"pira/cesta de luz com chamas subindo (energia/fogo)",
"fable-maestro-08":"laptop com card/cartao transparente (cartao/dados)",
"fable-maestro-09":"medidores/manometros ambar (velocimetros/medicao)",
"fable-maestro-10":"celular com bolhas/esferas saindo (IA no celular)",
"fable-maestro-11":"maestro regendo uma orquestra de robos num palco (orquestrar)",
# ---- persona (thumbs) ----
"persona-01":"fileiras de cards/telas iguais espelhados (clones/mesmice)",
"persona-02":"manequim/boneco neutro de pe (persona generica/avatar)",
"persona-03":"pessoa de luz entregando um card a um manequim (dar identidade/persona)",
"persona-04":"nuvem de fumaca com fragmentos (dispersao/ruido)",
"persona-05":"prateleiras com caixas e uma bola no chao (estoque/arquivo)",
"persona-06":"bloco de cristal ambar vs cubo de concreto (destaque vs comum)",
"persona-07":"chave ornamentada de luz (chave/acesso)",
"persona-08":"manequim vestindo uma faixa de luz/textura (vestir persona)",
"persona-09":"pergaminhos/rolos de luz girando (textos/personas)",
"persona-10":"mascara dourada dentro de uma esfera ambar num console (mascara/identidade)",
"persona-11":"pasta/folder de luz com documentos saindo (arquivos/personas)",
# ---- privado (thumbs) ----
"privado-01":"lanterna iluminando bolhas de chat no escuro (vazamento de conversas)",
"privado-02":"bolhas de chat gigantes rachando e desmoronando (conversas vazando)",
"privado-03":"icone de cadeado + compartilhar + olho (privacidade/exposto)",
"privado-04":"pessoa diante de um outdoor gigante de balao de chat (conversa exposta em publico)",
"privado-05":"vitrine de vidro com bolhas de chat expostas (conversas em exibicao)",
"privado-06":"lupa sobre uma plateia de bolhas de chat (buscar conversa)",
"privado-07":"mao robotica abrindo uma fechadura de luz (acesso/destravar)",
"privado-08":"mao tocando toggles de privacidade num celular (configurar privacidade)",
"privado-09":"balao de chat com relogio se desfazendo em particulas (conversa temporaria)",
"privado-10":"celular com bolhas de chat ambar saindo (mensagens)",
"privado-11":"cofre ambar com balao de chat dentro (conversa protegida)",
"privado-12":"celular com bolhas de chat ambar (mensagens)",
# ---- quanto-custa-a-hora (thumbs) ----
"quanto-custa-a-hora-01":"medalha/moeda dourada com rubi (valor/premio)",
"quanto-custa-a-hora-02":"dois homens de terno apertando as maos numa reuniao (acordo/negocio)",
"quanto-custa-a-hora-03":"pilha de moedas de luz sobre notas (dinheiro empilhado)",
"quanto-custa-a-hora-04":"homem de terno estressado numa mesa cheia de papeis (sobrecarga/caos)",
"quanto-custa-a-hora-05":"moeda gigante com circuito gravado (moeda tech/valor digital)",
"quanto-custa-a-hora-06":"homem de terno olhando tela holografica 'freed space' (liberar tempo)",
"quanto-custa-a-hora-07":"mulher numa videochamada com bandeira do Brasil (reuniao remota/equipe BR)",
# ---- radar (thumbs) ----
"radar-01":"mulher de terno segurando uma placa/pedra rachada (carregar peso/dado bruto)",
"radar-02":"figura humanoide com papeis voando ao redor (informacao espalhada)",
"radar-03":"pasta de luz com particulas/estrelas subindo (coletar/varrer dados)",
"radar-04":"antena parabolica/radar com telas de imagens ao redor (monitorar)",
"radar-05":"podio com cards e setas pra cima (ranking/destaque/subir)",
"radar-06":"documento central com conexoes pra icones ao redor (distribuir/conectar)",
"radar-07":"lupa sobre uma cidade de graficos de luz (buscar/analisar)",
"radar-08":"baloes de chat com um central vermelho rachado (alerta/conversa quebrada)",
"radar-09":"cards/janelas de luz flutuando sobre fumaca (feeds/posts)",
"radar-10":"aviao de papel de luz subindo entre baloes de chat (enviar/disparar)",
"radar-11":"celular com pasta/icone de luz (notificacao/app)",
# ---- reuniao-que-se-repete (thumbs) ----
"reuniao-que-se-repete-01":"mesa de reuniao oval cheia de telas vista de cima (reuniao/muitas telas)",
"reuniao-que-se-repete-02":"mao tocando uma pilha 'MONDAY MORNING MEETING' (reuniao de segunda/repeticao)",
"reuniao-que-se-repete-03":"sala de reuniao com pessoas e telao (reuniao corporativa)",
"reuniao-que-se-repete-04":"diagrama isometrico de processos/fluxo com icones (fluxo/operacao)",
"reuniao-que-se-repete-05":"cena industrial caotica com pessoas e fogo (caos/operacao pesada)",
"reuniao-que-se-repete-06":"homem pensando com engrenagem de dinheiro e tabuleiro de xadrez (estrategia/custo)",
"reuniao-que-se-repete-07":"palestrante num palco diante de parede de telas (apresentacao/palco)",
"reuniao-que-se-repete-08":"celular com tela 'Live Event' (evento ao vivo/transmissao)",
# ---- revisor (thumbs) ----
"revisor-01":"homem escrevendo com pena num documento de luz (escrever/revisar)",
"revisor-02":"homem numa mesa de vidro com documento de luz (revisar documento)",
"revisor-03":"homem sentado lendo/segurando um papel (ler/revisar)",
"revisor-04":"homem de pe ao lado de um pedestal com um card (avaliar/julgar)",
"revisor-05":"grade de cards com selos de aprovacao/checkmarks (aprovados/validados)",
"revisor-06":"fileira de cards com faiscas entre eles (conflito/revisao cruzada)",
"revisor-07":"duas pessoas em mesas opostas com portal de luz (revisao entre pares)",
"revisor-08":"feixe de luz de uma esfera ambar para um cubo azul (transferencia/contraste)",
"revisor-09":"homem com lupa examinando um card num pedestal (examinar/revisar)",
"revisor-10":"explosao de fragmentos a partir de um documento (erro/documento explodindo)",
"revisor-11":"aviao de papel de luz subindo entre colunas (enviar/publicar)",
# ---- segundo-cerebro (thumbs) ----
"segundo-cerebro-01":"papeis/cards voando espalhados no escuro (conhecimento espalhado)",
"segundo-cerebro-02":"figura humana caminhando deixando rastro de luz (jornada/aprendizado)",
"segundo-cerebro-03":"poliedro/cristal de luz ambar (nucleo de conhecimento)",
"segundo-cerebro-04":"relampago de luz sobre uma grade (conexao/insight)",
"segundo-cerebro-05":"cerebro feito de blocos dourados (conhecimento estruturado)",
"segundo-cerebro-06":"laptop com documento de luz (notas/documento)",
"segundo-cerebro-07":"nucleo/estrela com raios de luz saindo (centro de conhecimento/conexoes)",
"segundo-cerebro-08":"papeis e documento sobre uma mesa com luz (notas/documentos)",
"segundo-cerebro-09":"laptop com camadas de documentos de luz (organizar arquivos)",
"segundo-cerebro-10":"celular com esferas saindo num corredor de biblioteca (biblioteca/conhecimento)",
"segundo-cerebro-11":"corredor de biblioteca/arquivo de luz (biblioteca/arquivo)",
"segundo-cerebro-12":"celular num corredor de biblioteca com esferas (biblioteca no celular)",
"segundo-cerebro-13":"corredor de biblioteca/arquivo de luz (biblioteca/arquivo)",
}

if __name__ == "__main__":
    b = json.load(open("bank.json", encoding="utf-8"))
    n = 0
    for c in b["clips"]:
        if c["id"] in DESC:
            c["desc"] = DESC[c["id"]]; n += 1
    json.dump(b, open("bank.json", "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    print(f"descricoes precisas aplicadas: {n}/{len(b['clips'])}")
